#Made by BGHDNetwork(Noodles)
#=======================================================
#Plugin Page: https://www.spigotmc.org/resources/45655
#=======================================================
Update:
  Enabled: true
#antiexplosion.update
#Enables if there is a message on-join when the plugin is outdated. 
#=======================================================
